services:
  app:
    build: ./app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/usr/src/app
    networks:
      - my-network
    environment:
      TEST: test
      PORT: ${APP_PORT}
  nginx:
    image: nginx:1.21-alpine
    ports:
      - ${NGINX_PORT}:80
    networks:
      - my-network
    env_file: ./settings.env
    volumes:
      - ./nginx/html:/usr/share/nginx/html2
      - ./nginx/templates:/etc/nginx/templates

  

networks:
  my-network: {}