services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - my-network
    environment:
      TEST: test
      PORT: 8000
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8080:80
    networks:
      - my-network
    volumes:
      - ./nginx/html:/usr/share/nginx/html2
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  

networks:
  my-network: {}