services:
  app:
    build: ./app
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - my-network
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8080:80
    networks:
      - my-network
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  my-network:
